### ISSUE TITLE
Unable to download  - KeyError: 'force_change'

### ISSUE THREAD

**Issue by nocturneop15** [Kalanyr/gogrepoc#112]
Updating manifest works fine, but download does not. So far tried to delete manifest at all, verify all games with no positive impact. 

Error obtained: 
```
Traceback (most recent call last):
  File "D:\DATA\Hry\GOG\gogrepoc-master\gogrepoc.py", line 351, in __getattr__
    return self[key]
           ~~~~^^^^^
KeyError: 'force_change'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DATA\Hry\GOG\gogrepoc-master\gogrepoc.py", line 3980, in <module>
    main(process_argv(sys.argv))
  File "D:\DATA\Hry\GOG\gogrepoc-master\gogrepoc.py", line 3740, in main
    cmd_download(args.savedir, args.skipextras, args.skipids, args.dryrun, args.ids,args.os,args.lang,args.skipgalaxy,args.skipstandalone,args.skipshared, args.skipfiles,args.covers,args.backgrounds,args.downloadlimit)
  File "D:\DATA\Hry\GOG\gogrepoc-master\gogrepoc.py", line 2692, in cmd_download
    elif game_item.force_change == True:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Hry\GOG\gogrepoc-master\gogrepoc.py", line 353, in __getattr__
    raise AttributeError(key)
AttributeError: force_change
```

Python environment - Python 3.12.4
OS -  windows Server 2019 Std, windows server 2016 std, Windows 10 Pro

**Comment by nocturneop15** [comment]
https://github.com/dallemon/gogrepoc fork has fixed this error

**Comment by Kalanyr** [comment]
This should have been fixed by
https://github.com/Kalanyr/gogrepoc/commit/c453e922f94b3b55e67b65ad583320ff5fd08042
, can you verify that it still happens with the current version ?

You'll need to re-update any effected game for the fix to take effect.

Thanks,

**Comment by nocturneop15** [comment]
good work, looks fixed to me
