### ISSUE TITLE
Issues logging in

### ISSUE THREAD

**Issue by mrpijey** [Kalanyr/gogrepoc#115]
Installed all modules with pip, run the script. Asks for login, enter correct login information but get the following error.

`
22:04:14 | attempting gog login as 'foo@foo.com' ...
22:04:15 | fatal...
Traceback (most recent call last):
  File "G:\gogrepo.py", line 2342, in <module>
    main(process_argv(sys.argv))
  File "G:\gogrepo.py", line 2236, in main
    cmd_login(args.username, args.password)
  File "G:\gogrepo.py", line 946, in cmd_login
    with request(login_data['auth_url'], delay=0) as page:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\gogrepo.py", line 232, in request
    req = Request(url, data=enc_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (Utils)\Scripting Tools\Python\Lib\urllib\request.py", line 318, in __init__
    self.full_url = url
    ^^^^^^^^^^^^^
  File "C:\Program Files (Utils)\Scripting Tools\Python\Lib\urllib\request.py", line 344, in full_url
    self._parse()
  File "C:\Program Files (Utils)\Scripting Tools\Python\Lib\urllib\request.py", line 373, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'None'
`

**Comment by Kalanyr** [comment]
Apologies didn't see this. You're using the older no longer maintained version of gogrepo, you need to use gogrepoc.py from this repository ( or a fork of it )
