### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by ohjays** [Kalanyr/gogrepoc#40]
22:01:37 | loading local manifest...
22:01:38 | collecting md5 data out of the manifest
22:01:38 | fatal...
Traceback (most recent call last):
  File "/mnt/usb/gog/games - gog/downloader/gogrepoc.py", line 2777, in <module>
    main(process_argv(sys.argv))
  File "/mnt/usb/gog/games - gog/downloader/gogrepoc.py", line 2558, in main
    cmd_import(args.src_dir, args.dest_dir,args.os,args.lang,args.skipextras,args.skipids,args.ids,args.skipgalaxy,args.skipstandalone,args.skipshared)
  File "/mnt/usb/gog/games - gog/downloader/gogrepoc.py", line 1452, in cmd_import
    if game_item.md5 is not None:
UnboundLocalError: local variable 'game_item' referenced before assignment

**Comment by Kalanyr** [comment]
Thanks for the report, I'll upload a fix shortly.

**Comment by Kalanyr** [comment]
Please try the latest version and let me know if this is fixed, I believe
it should be.

**Comment by ohjays** [comment]
looks good, thanks

**Comment by Kalanyr** [comment]
Fixed
