### ISSUE TITLE
Games that cannot be downloaded through GOGRepoc or the GOG website

### ISSUE THREAD

**Issue by Kalanyr** [Kalanyr/gogrepoc#61]
Please use this thread to report items that can't be download through gogrepoc and also can't be downloaded via the GOG website.

**Comment by GenericJohnDoeNO0** [comment]
Dying light works again.

**Comment by Ygg01** [comment]
Got an exception when downloading ai_war_2
```
14:48:09 | request failed: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out. (3 retries left) -- will retry in 5s...
14:48:59 | request failed: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out. (2 retries left) -- will retry in 5s...
14:49:49 | request failed: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out. (1 retries left) -- will retry in 5s...
14:50:39 | unexpected connection error fetching md5 data for setup_ai_war_2_4.009_(64bit)_(54769).exe This error may be temporary. Please retry in 24 hours.
14:50:39 | The handled exception was:
14:50:39 |
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\gogrepoc\gogrepoc.py", line 229, in request
    response = session.get(url, params=args,stream=stream,timeout=HTTP_TIMEOUT)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\gogrepoc\gogrepoc.py", line 229, in request
    response = session.get(url, params=args,stream=stream,timeout=HTTP_TIMEOUT)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\gogrepoc\gogrepoc.py", line 229, in request
    response = session.get(url, params=args,stream=stream,timeout=HTTP_TIMEOUT)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\gogrepoc\gogrepoc.py", line 690, in fetch_file_info
    md5_response = request(updateSession,tmp_md5_url)
  File "C:\projects\gogrepoc\gogrepoc.py", line 243, in request
    return request(session=session,url=url, args=args, byte_range=byte_range, retries=retries-1, delay=HTTP_RETRY_DELAY)
  File "C:\projects\gogrepoc\gogrepoc.py", line 243, in request
    return request(session=session,url=url, args=args, byte_range=byte_range, retries=retries-1, delay=HTTP_RETRY_DELAY)
  File "C:\projects\gogrepoc\gogrepoc.py", line 243, in request
    return request(session=session,url=url, args=args, byte_range=byte_range, retries=retries-1, delay=HTTP_RETRY_DELAY)
  File "C:\projects\gogrepoc\gogrepoc.py", line 229, in request
    response = session.get(url, params=args,stream=stream,timeout=HTTP_TIMEOUT)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out.
14:50:39 | End exception report.```

**Comment by Wilstorm** [comment]
I would like to add Alien Isolation to the list that doesn't seem to work through gogrepoc.
